# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Experience
    url: /#papers
    weight: 20
  - name: Education
    url: /#talks
    weight: 30
  - name: Projects
    url: /#news
    weight: 40
  - name: Contacts
    url: experience/
    weight: 50

